name: Build & Deploy Microservices

on:
  push:
    brancHes: ["main"]

jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Connect To Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.USERNAME}}
          password:  ${{secrets.TOKEN}}

      - name: Build Stock Service
        run: docker build -t ${{ secrets.USERNAME }}/latihan_microservice_stock_image:latest ./stock

      - name: Push Stock Service
        run: docker push ${{ secrets.USERNAME }}/latihan_microservice_stock_image:latest

      - name: Build Order Service
        run: docker build -t ${{ secrets.USERNAME }}/latihan_microservice_order_image:latest ./order

      - name: Push Order Service
        run: docker push ${{ secrets.USERNAME }}/latihan_microservice_order_image:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Deploy Stock Service
        run: kubectl apply -f k8s/stock-kubernetes.yml

      - name: Deploy Order Service
        run: kubectl apply -f k8s/order-kubernetes.yml