name: Build & Deploy Microservices

on:
  push:
    brances: ["main"]

jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v4

      - name: Connect To Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.USERNAME }}
          password:  ${{ secrets.TOKEN }}

      - name: Build Stock Service
        run : docker build -t ${{ secrets.USERNAME }}/latihan_microservice_stock_image:latest ./stock

      - name: Push Stock Service
        run: docker push ${{ secrets.USERNAME }}/latihan_microservice_stock_image:latest

      - name: Build Order Service
        run : docker build -t ${{ secrets.USERNAME }}/latihan_microservice_order_image:latest ./order

      - name: Push Order Service
        run: docker push ${{ secrets.USERNAME }}/latihan_microservice_order_image:latest

      - name: Run Docker Compose
        run: |
          ssh user@server-ip << 'EOF'
            cd /home/app
            docker-compose pull
            docker-compose up -d
          EOF